services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./private/var/lib/pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
  taxi_ingest:
    image: taxi_ingest:v001
    depends_on:
      - pgdatabase
    command: >
      --user=root
      --password=root
      --host=pgdatabase
      --port=5432
      --db=ny_taxi
      --table_name=green_tripdata_2019-10
      --url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz
      --zipped=y
